name: "scaleway-container-deploy-action"
description: "This github action will help you to deploy automatically a container on Serverless Container"
inputs:
  type:
    description: "This input can be used for deploy or teardown your environment. type by default is deploy ( deploy | teadown )"
    required: false
    default: deploy
  scw_access_key:
    description: "Access Key ( https://console.scaleway.com/project/credentials )"
    required: true
  scw_secret_key:
    description: "secret key ( https://console.scaleway.com/project/credentials )"
    required: true
  scw_containers_namespace_id:
    description: "default namespace id where your container will be deploy, if this not required, this action will create a namespace and we need projectID to be set."
    required: true
  scw_registry:
    description: "From your scaleway registry ( format: rg.$REGION.scw.cloud/$NAMESPACE/$IMAGE:$TAG )"
    required: true
  scw_container_port:
    description: "Default port where your docker container expose"
    required: false
    default: "80"
  scw_memory_limit:
    description: "Memory limit in MB ( 128 | 256 | 512 | 1024 | 2048 )"
    required: false
    default: "256"
  scw_dns:
    description: "DNS name where your container will be available. Limitation: 63 char maximun"
    required: false
  scw_dns_prefix:
    description: "This will override prefix of your dns. if it's not set thane name of the containers ( max 34 char actually) will be set"
    required: false
  root_zone:
    description: "This will add ALIAS on your root zone. Actually CNAME is used for all `¨scw_dns_prefix.scw_dns` of your dns"
    required: false
    default: "false"
  scw_environment_variables:
    description: "List of environnment variables in the form of KEY=VALUE, separated by commas"
    required: false
    default: ""
  scw_secrets:
    description: "List of secrets in the form of KEY=VALUE, separated by commas"
    required: false
    default: ""

  # scw_debug:
  #   description: "debug log api call"
  #   required: false
  #   default: "0"

outputs:
  scw_namespace_id:
    description: "ID of your container namespace"
  scw_container_id:
    description: "ID of your container inside your namespace"
  container_url:
    description: "Url of your deployed container"
  url:
    description: "Url with dns set"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.type }}
    - ${{ inputs.scw_access_key }}
    - ${{ inputs.scw_secret_key }}
    - ${{ inputs.scw_containers_namespace_id }}
    - ${{ inputs.scw_registry }}
    - ${{ inputs.scw_container_port }}
    - ${{ inputs.scw_memory_limit }}
    - ${{ inputs.scw_dns }}
    - ${{ inputs.scw_dns_prefix }}
    - ${{ inputs.root_zone }}
    # - ${{ inputs.scw_debug }}
branding:
  icon: "cloud-lightning"
  color: "purple"
