name: "scaleway-container-deploy-action"
description: "This github action will help you to deploy automatically a container on Serverless Container"
inputs:
  type: 
    description: "This input can be used for deploy or teardown your environment. type by default is deploy ( deploy | teadown )"
    required: false
    default: deploy
  scw_access_key:
    description: "Access Key ( https://console.scaleway.com/project/credentials )"
    required: true
  scw_secret_key: 
    description: "secret key ( https://console.scaleway.com/project/credentials )"
    required: true
  # scw_project_id:
  #   description: "Project ID"
  #   required: true
  scw_containers_namespace_id:
    description: "default namespace id where your container will be deploy, if this not required, this action will create a namespace and we need projectID to be set."
    required: true
  scw_registry:
    description: "From your scaleway registry ( format: rg.$REGION.scw.cloud/$NAMESPACE/$IMAGE:$TAG )"
    required: true
  scw_container_port:
    description: "Default port where your docker container expose"
    required: false
    default: "80"
  scw_dns:
    description: "DNS name where your container will be available"
    required: false
  scw_dns_prefix:
    description: "DNS name where your container will be available"
    required: false
    
  # scw_debug:
  #   description: "debug log api call"
  #   required: false
  #   default: "0"

outputs:
  scw_namespace_id:
    description:  "ID of your container namespace"
  scw_container_id:
    description: "ID of your container inside your namespace"
  container_url: 
    description: 'Url of your deployed container'
  url:
    description: "Url with dns set"


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.type }}
    - ${{ inputs.scw_access_key }}
    - ${{ inputs.scw_secret_key }}
    # - ${{ inputs.scw_project_id }}
    - ${{ inputs.scw_containers_namespace_id }}
    - ${{ inputs.scw_registry }}
    - ${{ inputs.scw_container_port }}
    - ${{ inputs.scw_dns }}
    - ${{ inputs.scw_dns_prefix }}
    # - ${{ inputs.scw_debug }}

