export const ENV = {
  TYPE: 'INPUT_TYPE',
  ACCESS_KEY: 'INPUT_SCW_ACCESS_KEY',
  CONTAINER_NAMESPACE_ID: 'INPUT_SCW_CONTAINERS_NAMESPACE_ID',
  CONTAINER_PORT: 'INPUT_SCW_CONTAINER_PORT',
  DNS: 'INPUT_SCW_DNS',
  DNS_PREFIX: 'INPUT_SCW_DNS_PREFIX',
  REGION: 'INPUT_SCW_REGION',
  REGISTRY: 'INPUT_SCW_REGISTRY',
  PROJECT_ID: 'INPUT_SCW_PROJECT_ID',
  SECRET_KEY: 'INPUT_SCW_SECRET_KEY',
  MEMORY_LIMIT: 'INPUT_SCW_MEMORY_LIMIT',
  MIN_SCALE: 'INPUT_SCW_MIN_SCALE',
  MAX_SCALE: 'INPUT_SCW_MAX_SCALE',
  MAX_CONCURRENCY: 'INPUT_SCW_MAX_CONCURRENCY',
  CPU_LIMIT: 'INPUT_SCW_CPU_LIMIT',
  SANDBOX: 'INPUT_SCW_SANDBOX',
  ROOT_ZONE: 'INPUT_ROOT_ZONE',
  ENVIRONMENT_VARIABLES: 'INPUT_SCW_ENVIRONMENT_VARIABLES',
  SECRETS: 'INPUT_SCW_SECRETS',
} as const;

export const DEFAULTS = {
  DESCRIPTION: 'this container was created automatically by a github-action',
  PORT: 80,
  MIN_SCALE: 1,
  MAX_SCALE: 5,
  MAX_CONCURRENCY: 5,
  MEMORY_LIMIT: 256,
  CPU_LIMIT: 70,
  SANDBOX: 'v1',
  TIMEOUT_SECONDS: 60,
  REGION: 'fr-par',
  TYPE: 'deploy',
} as const;

export const DNS = {
  CNAME: 'CNAME',
  ALIAS: 'ALIAS',
  TTL: 360,
  WAIT_TIMEOUT: 15 * 60 * 1000,
  RETRY_INTERVAL: 5 * 1000,
} as const;

export const CONTAINER_NAME_MAX_LENGTH = 34;
export const HOSTNAME_MAX_LENGTH = 63;